//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oc.TSB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("oc.TSB.Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات مدیریتی.
        /// </summary>
        public static string AdminDescription {
            get {
                return ResourceManager.GetString("AdminDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوگل.
        /// </summary>
        public static string AuthenticationTypeGoogle {
            get {
                return ResourceManager.GetString("AuthenticationTypeGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داخلی.
        /// </summary>
        public static string AuthenticationTypepublic {
            get {
                return ResourceManager.GetString("AuthenticationTypepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string BaseTable {
            get {
                return ResourceManager.GetString("BaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اطلاعات پایه.
        /// </summary>
        public static string BaseTableType {
            get {
                return ResourceManager.GetString("BaseTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات ویجت ساز کموندا.
        /// </summary>
        public static string CamundaProssesSettings {
            get {
                return ResourceManager.GetString("CamundaProssesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  شماره تلفن همراه.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید شماره تلفن همراه.
        /// </summary>
        public static string CellPhoneNumberVerificationKey {
            get {
                return ResourceManager.GetString("CellPhoneNumberVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کامپوننت کموندا.
        /// </summary>
        public static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی فایل کامپوننت.
        /// </summary>
        public static string ComponentImageUrl {
            get {
                return ResourceManager.GetString("ComponentImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کامپوننت های کموندا.
        /// </summary>
        public static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کامپوننت.
        /// </summary>
        public static string ComponentType {
            get {
                return ResourceManager.GetString("ComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی تصویر کاور.
        /// </summary>
        public static string CoverImageUrl {
            get {
                return ResourceManager.GetString("CoverImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ایجاد.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string CreateOf {
            get {
                return ResourceManager.GetString("CreateOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ایجاد کننده.
        /// </summary>
        public static string CreatorUser {
            get {
                return ResourceManager.GetString("CreatorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان حذف .
        /// </summary>
        public static string DeleteDateTime {
            get {
                return ResourceManager.GetString("DeleteDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string DeleteOf {
            get {
                return ResourceManager.GetString("DeleteOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نشانی پست الکترونیکی.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید نشانی پست‌الکترونیکی.
        /// </summary>
        public static string EmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("EmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی تصویر.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ایجاد.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی‌پی.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه تایید شده است.
        /// </summary>
        public static string IsCellPhoneNumberVerified {
            get {
                return ResourceManager.GetString("IsCellPhoneNumberVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری حقوقی.
        /// </summary>
        public static string IsCompany {
            get {
                return ResourceManager.GetString("IsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی تایید شده است.
        /// </summary>
        public static string IsEmailAddressVerified {
            get {
                return ResourceManager.GetString("IsEmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ویژه بودن کاربر.
        /// </summary>
        public static string IsFeatured {
            get {
                return ResourceManager.GetString("IsFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی تایید شده.
        /// </summary>
        public static string IsNationalCodeVerified {
            get {
                return ResourceManager.GetString("IsNationalCodeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل عمومی است.
        /// </summary>
        public static string IsProfilePublic {
            get {
                return ResourceManager.GetString("IsProfilePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده تستی.
        /// </summary>
        public static string IsTestData {
            get {
                return ResourceManager.GetString("IsTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده تستی.
        /// </summary>
        public static string IsTrstData {
            get {
                return ResourceManager.GetString("IsTrstData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  غیر قابل حذف.
        /// </summary>
        public static string IsUndeletable {
            get {
                return ResourceManager.GetString("IsUndeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تایید شده.
        /// </summary>
        public static string IsVerified {
            get {
                return ResourceManager.GetString("IsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در صفحه تماس با ما.
        /// </summary>
        public static string IsVisibleInContactUsPage {
            get {
                return ResourceManager.GetString("IsVisibleInContactUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نام کلیدی.
        /// </summary>
        public static string KeyName {
            get {
                return ResourceManager.GetString("KeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین زمان تغییر گذرواژه.
        /// </summary>
        public static string LastChangePasswordDateTime {
            get {
                return ResourceManager.GetString("LastChangePasswordDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مدرک تحصیلی.
        /// </summary>
        public static string LastEducationDegree {
            get {
                return ResourceManager.GetString("LastEducationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان آخرین ورود.
        /// </summary>
        public static string LastLoginDateTime {
            get {
                return ResourceManager.GetString("LastLoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست.
        /// </summary>
        public static string ListOf {
            get {
                return ResourceManager.GetString("ListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست {0}.
        /// </summary>
        public static string ListOfItems {
            get {
                return ResourceManager.GetString("ListOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ورود.
        /// </summary>
        public static string LoginType {
            get {
                return ResourceManager.GetString("LoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان خروج از سامانه.
        /// </summary>
        public static string LogoutDateTime {
            get {
                return ResourceManager.GetString("LogoutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  وضعیت تاهل.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نظام وظیفه.
        /// </summary>
        public static string MilitaryServiceStatus {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چیدمان.
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کامپوننت والد.
        /// </summary>
        public static string ParentComponentName {
            get {
                return ResourceManager.GetString("ParentComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرایند.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرایندها.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرایند.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی‌پی کاربر در زمان ثبت‌نام.
        /// </summary>
        public static string RegisterIP {
            get {
                return ResourceManager.GetString("RegisterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نوع ثبت‌نام در سامانه.
        /// </summary>
        public static string RegisterType {
            get {
                return ResourceManager.GetString("RegisterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مذهب.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربر.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه ای را انتخاب نمایید.
        /// </summary>
        public static string SelectAnItem {
            get {
                return ResourceManager.GetString("SelectAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن ثابت.
        /// </summary>
        public static string TelNumber {
            get {
                return ResourceManager.GetString("TelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ویرایش.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ویرایش.
        /// </summary>
        public static string UpdateDateTime {
            get {
                return ResourceManager.GetString("UpdateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string UpdateOf {
            get {
                return ResourceManager.GetString("UpdateOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ویرایش کننده.
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم کموندا.
        /// </summary>
        public static string UserTask {
            get {
                return ResourceManager.GetString("UserTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرم کموندا.
        /// </summary>
        public static string UserTaskName {
            get {
                return ResourceManager.GetString("UserTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم های کموندا.
        /// </summary>
        public static string UserTasks {
            get {
                return ResourceManager.GetString("UserTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورژن.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
